# Generated by Django 4.2.25 on 2025-10-24 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='food_item',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('started', 'Started'), ('reached', 'Reached'), ('collected', 'Collected'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
    ]
